### ISSUE TITLE
LLVM Build Error:

### ISSUE THREAD

**Issue by jeffreytakahashi** [connorkuehl/clang_randstruct#26]
This is a screenshot of the error that I had. I finally spoke with my friend, but I have not had a chance to sit down and poke at this. She told me:

"FileOutputBuffer::discard() was added to llvm in August. I'm gonna assume you've downloaded some dependency that's newer than that date that's trying to compile with llvm but the version of llvm you have is older than that date."

I was directed to read the following and will do so hopefully tonight.

https://github.com/llvm-mirror/llvm/commit/5cd279703c599cb0b2ad4f163374a10e97c8a954

![received_564033900725019](https://user-images.githubusercontent.com/40756056/49323966-43f4d700-f4d9-11e8-957f-a53986804cf1.png)

**Comment by connorkuehl** [comment]
It looks like you've checked out `compiler-rt` and `libcxx`. I don't think these are necessary for our work. I omitted them since they're optional. It looks like these are where the issues are originating for you. Try building just LLVM and Clang and skip the instructions marked as optional here: https://clang.llvm.org/get_started.html

**Comment by tim-pugh** [comment]
closing.
