### ISSUE TITLE
Accept command line arguments

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/clang_randstruct#46]
The plugin will need to accept a seed value from the user (command line).

There's already example code in the prototype for parsing and accepting these arguments.

**Comment by jeffreytakahashi** [comment]
This might require further digging or talking to Kees, but in Randstruct, there is a randomize_layout_seed.h that contains the seed and is then accessible. The gen-random-seed is a shell script that just gets and sets a value. Is there a time that we would need to pass a value around rather than just use one as set?

**Comment by tim-pugh** [comment]
It looks like there is an easy method to pass it in.I just need to toy with the Makefile more but will follow Kees's gcc plugin work and set it in the same fashion.

**Comment by tim-pugh** [comment]
In the makefile you can now set the `RAND-SEED` variable to the integer value you'd like to pass to rand-seed.py.

`RAND-SEED-SCRIPT` will run the python code.

You can see commit #64 for the commit.
